# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [1]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [1]:
import numpy as np

In [2]:
array = np.arange(1000000)
lista = list(range(1000000))

In [3]:
%time for _ in range(10): array_2 = array * 2
%time for _ in range(10): lista_2 = [x * 2 for x in lista]

CPU times: user 31.5 ms, sys: 3.92 ms, total: 35.4 ms
Wall time: 54.7 ms
CPU times: user 511 ms, sys: 59.9 ms, total: 571 ms
Wall time: 572 ms


### Exercício 2

In [4]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [5]:
import numpy as np

In [6]:
array = np.arange(10)

In [7]:
array[5:9] = 0

In [8]:
array

array([0, 1, 2, 3, 4, 0, 0, 0, 0, 9])

### Exercício 3

In [37]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

In [11]:
import numpy as np
array_3d = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

In [12]:
array_3d

array([[[1, 1, 1],
        [2, 2, 2]],

       [[3, 3, 3],
        [4, 4, 4]]])

In [13]:
array_3d[0]

array([[1, 1, 1],
       [2, 2, 2]])

### Exercício 4

In [45]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [46]:
import numpy as np

In [49]:
array_2d = np.array([[1,1,1],[2,2,2],[3,3,3]])

In [51]:
# Imprima os elementos da terceira linha da matriz
array_2d[2]

array([3, 3, 3])

In [54]:
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas
array_2d[:2,1:]

array([[1, 1],
       [2, 2]])

### Exercício 5

In [55]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [57]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [60]:
resposta = [(x if z else y) for x, y, z in zip(xarr, yarr, cond)]
resposta

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [61]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

In [62]:
A = np.arange(10)
np.save('arrayA', A)
print(A)

[0 1 2 3 4 5 6 7 8 9]


In [63]:
B = np.load('arrayA.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [64]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

In [66]:
unico = obj.unique()
unico

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [68]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [69]:
data = resp.json()

In [70]:
frame = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
frame

number                                              title  \
0    26490  RecursionError when selecting single column fr...   
1    26488    Set single cell of Multindex DataFrame to array   
2    26487                        Please stop relying on xlrd   
3    26486        DOC/CLN: Change API reference section title   
4    26485         A memory leak when using bottleneck nanmax   
5    26483  Better error message for DataFrame.hist() with...   
6    26480  pd.DataFrame.dot does not work when column ind...   
7    26477                                CLN: pd.TimeGrouper   
8    26476  Standard Error of the Mean Unavailable in Roll...   
9    26475  df.groupby on a column with complex numbers is...   
10   26474  Fix the output of df.describe on an empty cate...   
11   26473                Excel Test Cleanup - ReadWriteClass   
12   26472  Non-expected NaN numbers behavior for  .dropna...   
13   26471  Fix bug where list like object not returning e...   
14   26469  BUG: Series construction with EA dtype and ind...   
15   26468  BUG: setitem with boolean mask and series as v...   
16   26464                  CLN: Remove ExcelWriter.sheetname   
17   26463  Fix 'observed' kwarg not doing anything on Ser...   
18   26462  `groupby` in combination with `rolling` provid...   
19   26460  unhelpful error message with DataFrame constru...   
20   26459  DataFrame constructor with MultiIndex DataFram...   
21   26458     Remove py.path special handling from io.common   
22   26456  BUG-26214 fix colors parameter in DataFrame.bo...   
23   26455  BUG: Fix for pd.read_fwf not reading addinfour...   
24   26454   GroupBy nth with Categorical, NA Data and dropna   
25   26453             Replace Union annotations with TypeVar   
26   26450                          Deprecate py.path support   
27   26449                                   Annotate to_json   
28   26446  to_csv with UTF16 Incorrectly Treats BOM as co...   
29   26443  Py3 Failed to read HDF5 created in Py2 with da...   

                                               labels state  
0                                                  []  open  
1                                                  []  open  
2   [{'id': 49254273, 'node_id': 'MDU6TGFiZWw0OTI1...  open  
3                                                  []  open  
4                                                  []  open  
5   [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
6                                                  []  open  
7   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
8                                                  []  open  
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
10  [{'id': 47223669, 'node_id': 'MDU6TGFiZWw0NzIy...  open  
11  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
12  [{'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc...  open  
13  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
14  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
15  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
16  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
17  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
18  [{'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc...  open  
19                                                 []  open  
20                                                 []  open  
21  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
22  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
23  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
24  [{'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUy...  open  
25  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
26  [{'id': 49747336, 'node_id': 'MDU6TGFiZWw0OTc0...  open  
27  [{'id': 1280988427, 'node_id': 'MDU6TGFiZWwxMj...  open  
28  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
29  [{'id': 47229190, 'node_id': 'MDU6TGFiZWw0NzIy...  open

### Exercício 10

In [71]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

In [14]:
import sqlite3
import pandas as pd

query = "CREATE TABLE exercicio_10 (nome VARCHAR(50), idade INTEGER);"

con = sqlite3.connect('dsa.db')
con.execute(query)
con.commit()

In [17]:
data = [('Wellyson Martins',31),('Mônica Martins',33)]

stmt = "INSERT INTO exercicio_10 VALUES (?, ?)"
con.executemany(stmt, data)
con.commit()

In [18]:
cursor = con.execute('SELECT * FROM exercicio_10')
rows = cursor.fetchall()
rows

[('Wellyson Martins', 31), ('Mônica Martins', 33)]

In [20]:
pd.DataFrame(rows, columns = [x[0] for x in cursor.description])

nome  idade
0  Wellyson Martins     31
1    Mônica Martins     33

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>